{"name": "test_xfail_do_not_raise_mentioned_exception", "status": "passed", "description": "\n    >>> import pytest\n\n    >>> @pytest.mark.xfail(raises=AssertionError)\n    ... def test_xfail_do_not_raise_mentioned_exception_example():\n    ...     pass\n    ", "attachments": [{"name": "stdout", "source": "a20bf015-3e29-4c12-a900-73c1e8b5c557-attachment.txt", "type": "text/plain"}], "start": 1710872970267, "stop": 1710872970288, "uuid": "a37f9918-1391-4606-b18d-a8c18df85d48", "historyId": "a6d88e51310283a00db39e0da430f16a", "testCaseId": "a6d88e51310283a00db39e0da430f16a", "fullName": "tests.allure_pytest.acceptance.status.xfail_call_status_test#test_xfail_do_not_raise_mentioned_exception", "labels": [{"name": "parentSuite", "value": "tests.allure_pytest.acceptance.status"}, {"name": "suite", "value": "xfail_call_status_test"}, {"name": "host", "value": "MacBook-Pro-whenessel.local"}, {"name": "thread", "value": "29518-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.allure_pytest.acceptance.status.xfail_call_status_test"}]}