{"name": "test_xfail_with_reason_raise_mentioned_exception", "status": "passed", "description": "\n    >>> import pytest\n\n    >>> @pytest.mark.xfail(raises=AssertionError, reason='Some reason')\n    ... def test_xfail_with_reason_raise_mentioned_exception_example():\n    ...     assert False\n\n    ", "attachments": [{"name": "stdout", "source": "baa49def-1665-4783-9b1e-147e7ab64d13-attachment.txt", "type": "text/plain"}], "start": 1710872970214, "stop": 1710872970236, "uuid": "d1032ccd-7f1c-4705-b350-4b8c9fce64eb", "historyId": "191f704bcdc1d6e9b51e864496f12bab", "testCaseId": "191f704bcdc1d6e9b51e864496f12bab", "fullName": "tests.allure_pytest.acceptance.status.xfail_call_status_test#test_xfail_with_reason_raise_mentioned_exception", "labels": [{"name": "parentSuite", "value": "tests.allure_pytest.acceptance.status"}, {"name": "suite", "value": "xfail_call_status_test"}, {"name": "host", "value": "MacBook-Pro-whenessel.local"}, {"name": "thread", "value": "29518-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.allure_pytest.acceptance.status.xfail_call_status_test"}]}