{"name": "test_xfail_with_reason_do_not_raise_mentioned_exception", "status": "passed", "description": "\n    >>> import pytest\n\n    >>> @pytest.mark.xfail(raises=AssertionError, reason=\"Some reason\")\n    ... def test_xfail_with_reason_do_not_raise_mentioned_exception_example():\n    ...     pass\n    ", "attachments": [{"name": "stdout", "source": "fa34b81b-00ef-4451-927f-bd1c2fa35904-attachment.txt", "type": "text/plain"}], "start": 1710872970293, "stop": 1710872970312, "uuid": "d41839ca-1963-48dd-abda-a754ae067b04", "historyId": "ebccfeb6fb5e0ace08f08a616f54f3b0", "testCaseId": "ebccfeb6fb5e0ace08f08a616f54f3b0", "fullName": "tests.allure_pytest.acceptance.status.xfail_call_status_test#test_xfail_with_reason_do_not_raise_mentioned_exception", "labels": [{"name": "parentSuite", "value": "tests.allure_pytest.acceptance.status"}, {"name": "suite", "value": "xfail_call_status_test"}, {"name": "host", "value": "MacBook-Pro-whenessel.local"}, {"name": "thread", "value": "29518-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.allure_pytest.acceptance.status.xfail_call_status_test"}]}